### ISSUE TITLE
Streaming Video Question

### ISSUE THREAD

**Issue by narniaexpert** [derekmolloy/boneCV#3]
@derekmolloy,

Thank you for providing your video and code for getting video from the web camera into the micro controller. My goal is to connect the micro controller to a WiFi network to have live streaming video for the control of a robot. We have a separate micro controller dedicated for sending the video. We would like a phone or computer on the WiFi network to be able to stream the video. I was just wondering if you had any suggestions on how to accomplish live streaming video from the micro controller? This repository provides a great foundation for capturing content from the HD webcam, but I would appreciate any advice on how you would suggest to prepare a video feed for streaming.

Thank you very much,
@NarniaExpert

**Comment by derekmolloy** [comment]
@narniaexpert I have implemented this in the project. Have a look at: http://derekmolloy.ie/beaglebone/beaglebone-black-streaming-video-tutorial/

Kind regards, Derek.
