### ISSUE TITLE
Error while running the capture.c file

### ISSUE THREAD

**Issue by itsashis4u** [derekmolloy/boneCV#4]
While running the command `./capture -Fc 600 -o > output.raw`
I get an error saying `select timeout`

I did what it has been said in the video.
Is there anything wrong in my approach?

Please let me know if I am wrong

Attached screenshot of the error

Thank You 

![beagle](https://cloud.githubusercontent.com/assets/4126695/6431736/f5a8c7a2-c05f-11e4-9ed5-01c747c97080.png)

**Comment by derekmolloy** [comment]
You need to change the time-out properties of the uvcvideo LKM as follows:
molloyd@beaglebone:∼$ sudo rmmod uvcvideo
molloyd@beaglebone:∼$ sudo modprobe uvcvideo nodrop=1 timeout=5000
molloyd@beaglebone:∼$ lsmod |grep uvcvideo
uvcvideo 57013 0
videobuf2_vmalloc 2490 1 uvcvideo

**Comment by kmontep** [comment]
Thank you
Montep
